### ISSUE TITLE
CebuloBoy na Windowsie

### ISSUE THREAD

**Issue by enkryptajz** [Behoston/CebuloBoy#26]
Hej,
mam jedno małe pytanko. Czy da się w jakiś sposób uruchomić CebuloBoya na Windowsie? Chodzi mi konkretnie o plik konfiguracyjny dotyczący CRON'a. Nawet mi wystarczy jakaś podpowiedź. Czekam na odpowiedź. :)

**Comment by Behoston** [comment]
Na pewno da się go uruchomić, jeśli tylko masz możliwość zainstalowania Pythona wraz z potrzebnymi paczkami. Co do CRONa na Windowsie, to chyba odpowiednikiem jest `Windows Task Scheduler`, ale niestety nie wiem jak go skonfigurować. 
Z tego, co szybko poszukałem to: https://pypi.org/project/python-crontab/ powinno obsługiwać pliki w formacie takim samym jak CRON, ale to wymaga działania programu w tle.
