### ISSUE TITLE
TG i x-kom

### ISSUE THREAD

**Issue by qwinto** [Behoston/CebuloBoy#27]
TG wysyła poprzednią promocję x-kom, już nie aktualną zamiast bieżącej.

**Comment by Behoston** [comment]
Kiedyś to naprawię, możliwe, że wystarczy odpalić drugi raz, bo x-kom się spóźnia

**Comment by Behoston** [comment]
Dorzuciłem odpalanie o 01, może to powodować ewentualne wyścigi, bo baza to sqlite, ale liczę, że raczej będzie śmigać, na więcej aktualnie nie za bardzo mam czas/siłę/ochotę/cokolwiek.

**Comment by Behoston** [comment]
Chyba pomogło
