### ISSUE TITLE
X-kom/al.to czasem nie wypala

### ISSUE THREAD

**Issue by Behoston** [Behoston/CebuloBoy#5]
Nie wiem z jakiego powodu, ale czasami nie jest uruchamiany skrypt do pobierania z x-koma/alto, lub są uruchamiane, ale umierają. Logi niewiele mówią (trzeba dodać do logowania timestampy)

**Comment by Behoston** [comment]
Kończy się RAM i SWAP. Rozważam: 

- zrzutkę na coś ciut mocniejszego (aruba 5zł/mieś)
- wypróbowanie czegoś taniego (http://lowendstock.com/)
- kolejkowanie scrapowania
- przepisanie kodu na asynchroniczny

**Comment by ad-m** [comment]
Ja sugeruje przenieść to na AWS Lambda. Nie będziesz miał kosztów, bo bez problemu zmieścisz się w free tier. Służę konsultacją jak to zrobić technicznie.

Tu przykład bota: https://github.com/serverless/examples/tree/master/aws-python-telegram-bot

Do działania bota potrzebujesz:
- AWS CloudWatch Events (cykliczne wywołanie) - cron,
- AWS Lambda (środowisko wykonawcze),
- jakiejś bazy danych - https://aws.amazon.com/free/database/

**Comment by Behoston** [comment]
Prywatnie nie lubię się z AWSem. Używałem sobie wesoło free tiera z kredytami z githuba na cele mojego licencjatu (t2.micro na bazę danych z wynikami + stronka do prezentacji), po czym kredyty nagle zniknęły (brak śladu w profilu) a AWS próbował mi chargować kartę, support nie pomógł, więc dałem za wygraną.
Wolę dać te kilka dolców i mieć fixed price bez niespodzianek albo upchnąć gdzieś bota obok innych projektów (co właśnie robię, bo mikrus padł).

**Comment by Behoston** [comment]
https://github.com/Behoston/CebuloBoy/commit/c7eff734ba3fb938cd9eed70492262b83cb45c96
